name: CI for PRs
on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      CARGO_INCREMENTAL: 0
      SVDTOOLS: svdtools

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Install tools
        run: ./generator/scripts/tool_install.sh

      - name: Install Python dependencies
        run: |
          pip3 install --user setuptools wheel
          pip3 install --user -r requirements.txt

      - name: Build
        run: |
          cd svd
          ./extract.sh
          cd ..
          ./build.py
